### ISSUE TITLE
In Node containers which are build in indy-tutorial-sandbox are crashing. 

### ISSUE THREAD

**Issue by Dpkkmr** [brycecurtis/indy-tutorial-sandbox#6]
When I am creating the Nodes cluster, all nodes in the cluster are exiting with this exception in each node container logs: 

Proof of possession for BLS key is RPLagxaR5xdimFzwmzYnz4ZhWtYQEj8iR5ZU53T2gitPCyCHQneUn2Huc4oeLd2B2HzkGnjAff4hWTJT6C7qHYB1Mv2wU5iHHGFWkhnTX9WsEAbunJCV2qcaXScKj4tTfvdDKfLiVuU2av6hbsMztirRze7LvYBkRHV3tGwyCptsrP
Traceback (most recent call last):
File "/usr/local/bin/start_indy_node", line 12, in <module>
raise Exception("Provide name and two pairs of IP/port for running the node "
Exception: Provide name and two pairs of IP/port for running the node and client stacks in form 'node_name node_ip node_port client_ip client_port'

c211c7037b82 indy-base "/bin/bash -c 'creat…" 4 minutes ago Exited (1) 4 minutes ago Node4
f29e84e71826 indy-base "/bin/bash -c 'creat…" 4 minutes ago Exited (1) 4 minutes ago Node3
a7ba9d57712a indy-base "/bin/bash -c 'creat…" 4 minutes ago Exited (1) 4 minutes ago Node2
45008dd837f7 indy-base "/bin/bash -c 'creat…" 4 minutes ago Exited (1) 4 minutes ago Node1

**Comment by brycecurtis** [comment]
The arguments for start_indy_node were changed in indy-node repo, which required an update to makefile.  Please try with latest code.

**Comment by Dpkkmr** [comment]
Thanks, issue is resolved.
